apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ansible-test-pr-
spec:
  pipelineRef:
    name: ansible-test-automation
  params:
    - name: project-dir
      value: /workspace/runner-dir/dn
    - name: args
      value:
      - -p
      - builder.yaml
  workspaces:
  - name: runner-dir
    persistentVolumeClaim:
      claimName: shared-task-storage
