apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ansible-test-pr-
spec:
  pipelineRef:
    name: ansible-test-automation
  params:
    - name: project-dir
      value: ansible
    - name: args
      value:
      - -p
      - Ansible_Test.yml
  workspaces:
  - name: runner-dir
    persistentVolumeClaim:
      claimName: shared-task-storage-2
