apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: ansible-test-pr-
spec:
  pipelineRef:
    name: ansible-test-automation
  params:
    - name: project-dir
      value: dn/demo/project
    - name: args
      value:
      - -p
      - builder.yaml
      - --inventory
      - /workspace/runner-dir/dn/demo/inventory/openshift.yml
      - -vvv
  workspaces:
  - name: runner-dir
    persistentVolumeClaim:
      claimName: shared-task-storage
